/* AUTO-GENERATED by tools/thumb2c.py — do not edit. */
#include "../common.h"
#include "../cpu.h"
#include "../gba_memory.h"

extern u32 aot_read32(u32);
extern u16 aot_read16(u32);
extern u8  aot_read8 (u32);
extern void aot_write32(u32, u32);
extern void aot_write16(u32, u16);
extern void aot_write8 (u32, u8);

/* Flag computation helpers — match ARM7TDMI semantics. */
#define SET_NZ(x) do { u32 _x=(u32)(x); nf=(_x>>31)&1u; zf=(_x==0); } while(0)
#define ADD_FLAGS(d,a,b) do { u32 _a=(a),_b=(b),_d=(d); \
    nf=(_d>>31)&1u; zf=(_d==0); \
    cf=(_d<_a); \
    vf=(((_a^_d)&(_b^_d))>>31)&1u; } while(0)
#define SUB_FLAGS(d,a,b) do { u32 _a=(a),_b=(b),_d=(d); \
    nf=(_d>>31)&1u; zf=(_d==0); \
    cf=(_a>=_b); \
    vf=(((_a^_b)&(_a^_d))>>31)&1u; } while(0)
#define LSL_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(32-_n))&1u; \
    SET_NZ(d); } while(0)
#define LSR_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(_n-1))&1u; \
    SET_NZ(d); } while(0)
#define ASR_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(_n-1))&1u; \
    SET_NZ(d); } while(0)

/* BAIL: write all state back, set PC to bail addr, return so the
 * interpreter can resume. */
#define BAIL(addr) do { \
    reg[0]=r0; reg[1]=r1; reg[2]=r2; reg[3]=r3; \
    reg[4]=r4; reg[5]=r5; reg[6]=r6; reg[7]=r7; \
    reg[8]=r8; reg[9]=r9; reg[10]=r10; reg[11]=r11; reg[12]=r12; \
    reg[13]=sp; reg[14]=lr; reg[REG_PC]=(addr); \
    reg[REG_C_FLAG]=cf; reg[REG_N_FLAG]=nf; \
    reg[REG_Z_FLAG]=zf; reg[REG_V_FLAG]=vf; \
    return; \
} while(0)

/* Function return: PC = LR & ~1, write back regs, return. */
#define AOT_RETURN() do { \
    reg[0]=r0; reg[1]=r1; reg[2]=r2; reg[3]=r3; \
    reg[4]=r4; reg[5]=r5; reg[6]=r6; reg[7]=r7; \
    reg[8]=r8; reg[9]=r9; reg[10]=r10; reg[11]=r11; reg[12]=r12; \
    reg[13]=sp; reg[14]=lr; reg[REG_PC]=lr & ~1u; \
    reg[REG_C_FLAG]=cf; reg[REG_N_FLAG]=nf; \
    reg[REG_Z_FLAG]=zf; reg[REG_V_FLAG]=vf; \
    return; \
} while(0)

/* function 0x0806F160: 76 insns, 4 branch targets, 0 BL continuations */
static void aot_gen_0806F160(u32 ep) {
    u32 r0 = reg[0];
    u32 r1 = reg[1];
    u32 r2 = reg[2];
    u32 r3 = reg[3];
    u32 r4 = reg[4];
    u32 r5 = reg[5];
    u32 r6 = reg[6];
    u32 r7 = reg[7];
    u32 r8 = reg[8];
    u32 r9 = reg[9];
    u32 r10 = reg[10];
    u32 r11 = reg[11];
    u32 r12 = reg[12];
    u32 sp = reg[13];
    u32 lr = reg[14];
    u32 cf = reg[REG_C_FLAG], nf = reg[REG_N_FLAG];
    u32 zf = reg[REG_Z_FLAG], vf = reg[REG_V_FLAG];
    (void)cf; (void)nf; (void)zf; (void)vf;
    /* 0806F160: push {r4, r5, r6, r7, lr} */
    sp -= 20u;
    aot_write32(sp + 0u, r4);
    aot_write32(sp + 4u, r5);
    aot_write32(sp + 8u, r6);
    aot_write32(sp + 12u, r7);
    aot_write32(sp + 16u, lr);
    /* 0806F162: mov r7, sl */
    r7 = r10;
    /* 0806F164: mov r6, sb */
    r6 = r9;
    /* 0806F166: mov r5, r8 */
    r5 = r8;
    /* 0806F168: push {r5, r6, r7} */
    sp -= 12u;
    aot_write32(sp + 0u, r5);
    aot_write32(sp + 4u, r6);
    aot_write32(sp + 8u, r7);
    /* 0806F16A: adds r6, r0, #0 */
    { u32 _a=r0, _b=0x0u; r6=_a+_b; ADD_FLAGS(r6,_a,_b); }
    /* 0806F16C: ldrb r0, [r6] */
    r0 = aot_read8(r6);
    /* 0806F16E: lsls r0, r0, #0x1c */
    r0 = (r0 << 28);
    LSL_FLAGS(r0, r0, 28);
    /* 0806F170: movs r4, #0 */
    r4 = 0x0u;
    SET_NZ(r4);
    /* 0806F172: cmp r0, #0 */
    { u32 _a=r0, _b=0x0u, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 0806F174: beq #0x806f1ea */
    if (zf) goto L0806F1EA;
L0806F176:
    /* 0806F176: ldr r0, [r6, #0xc] */
    r0 = aot_read32((r6 + 12u));
    /* 0806F178: lsls r2, r4, #1 */
    r2 = (r4 << 1);
    LSL_FLAGS(r2, r4, 1);
    /* 0806F17A: adds r1, r2, r4 */
    { u32 _a=r2, _b=r4; r1=_a+_b; ADD_FLAGS(r1,_a,_b); }
    /* 0806F17C: lsls r1, r1, #3 */
    r1 = (r1 << 3);
    LSL_FLAGS(r1, r1, 3);
    /* 0806F17E: adds r0, r1, r0 */
    { u32 _a=r1, _b=r0; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F180: ldr r3, [pc, #0x74] */
    r3 = aot_read32(0x806F1F8u);
    /* 0806F182: adds r1, r1, r3 */
    { u32 _a=r1, _b=r3; r1=_a+_b; ADD_FLAGS(r1,_a,_b); }
    /* 0806F184: ldm r1!, {r3, r5, r7} */
    r3 = aot_read32(r1 + 0u);
    r5 = aot_read32(r1 + 4u);
    r7 = aot_read32(r1 + 8u);
    r1 += 12u;
    /* 0806F186: stm r0!, {r3, r5, r7} */
    aot_write32(r0 + 0u, r3);
    aot_write32(r0 + 4u, r5);
    aot_write32(r0 + 8u, r7);
    r0 += 12u;
    /* 0806F188: ldm r1!, {r3, r5, r7} */
    r3 = aot_read32(r1 + 0u);
    r5 = aot_read32(r1 + 4u);
    r7 = aot_read32(r1 + 8u);
    r1 += 12u;
    /* 0806F18A: stm r0!, {r3, r5, r7} */
    aot_write32(r0 + 0u, r3);
    aot_write32(r0 + 4u, r5);
    aot_write32(r0 + 8u, r7);
    r0 += 12u;
    /* 0806F18C: movs r5, #0 */
    r5 = 0x0u;
    SET_NZ(r5);
    /* 0806F18E: ldrb r3, [r6, #1] */
    r3 = aot_read8((r6 + 1u));
    /* 0806F190: ldr r7, [r6, #0xc] */
    r7 = aot_read32((r6 + 12u));
    /* 0806F192: mov sb, r7 */
    r9 = r7;
    /* 0806F194: mov r8, r2 */
    r8 = r2;
    /* 0806F196: ldr r0, [r6, #0x10] */
    r0 = aot_read32((r6 + 16u));
    /* 0806F198: mov ip, r0 */
    r12 = r0;
    /* 0806F19A: adds r1, r4, #1 */
    { u32 _a=r4, _b=0x1u; r1=_a+_b; ADD_FLAGS(r1,_a,_b); }
    /* 0806F19C: mov sl, r1 */
    r10 = r1;
    /* 0806F19E: cmp r5, r3 */
    { u32 _a=r5, _b=r3, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 0806F1A0: bhs #0x806f1c8 */
    if (cf) goto L0806F1C8;
    /* 0806F1A2: mov r7, ip */
    r7 = r12;
    /* 0806F1A4: ldr r1, [r6, #8] */
    r1 = aot_read32((r6 + 8u));
    /* 0806F1A6: lsls r0, r4, #2 */
    r0 = (r4 << 2);
    LSL_FLAGS(r0, r4, 2);
    /* 0806F1A8: adds r0, r0, r1 */
    { u32 _a=r0, _b=r1; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F1AA: ldr r2, [r0] */
    r2 = aot_read32(r0);
L0806F1AC:
    /* 0806F1AC: adds r0, r4, #0 */
    { u32 _a=r4, _b=0x0u; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F1AE: muls r0, r3, r0 */
    r0 = r3 * r0;
    SET_NZ(r0);
    /* 0806F1B0: adds r0, r0, r5 */
    { u32 _a=r0, _b=r5; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F1B2: lsls r0, r0, #3 */
    r0 = (r0 << 3);
    LSL_FLAGS(r0, r0, 3);
    /* 0806F1B4: adds r0, r0, r7 */
    { u32 _a=r0, _b=r7; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F1B6: lsls r1, r5, #0xb */
    r1 = (r5 << 11);
    LSL_FLAGS(r1, r5, 11);
    /* 0806F1B8: adds r1, r2, r1 */
    { u32 _a=r2, _b=r1; r1=_a+_b; ADD_FLAGS(r1,_a,_b); }
    /* 0806F1BA: str r1, [r0] */
    aot_write32(r0, r1);
    /* 0806F1BC: adds r0, r5, #1 */
    { u32 _a=r5, _b=0x1u; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 0806F1BE: lsls r0, r0, #0x10 */
    r0 = (r0 << 16);
    LSL_FLAGS(r0, r0, 16);
    /* 0806F1C0: lsrs r5, r0, #0x10 */
    r5 = (r0 >> 16);
    LSR_FLAGS(r5, r0, 16);
    /* 0806F1C2: ldrb r3, [r6, #1] */
    r3 = aot_read8((r6 + 1u));
    /* 0806F1C4: cmp r5, r3 */
    { u32 _a=r5, _b=r3, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 0806F1C6: blo #0x806f1ac */
    if (!cf) goto L0806F1AC;
L0806F1C8:
    /* 0806F1C8: mov r3, r8 */
    r3 = r8;
    /* 0806F1CA: adds r1, r3, r4 */
    { u32 _a=r3, _b=r4; r1=_a+_b; ADD_FLAGS(r1,_a,_b); }
    /* 0806F1CC: lsls r1, r1, #3 */
    r1 = (r1 << 3);
    LSL_FLAGS(r1, r1, 3);
    /* 0806F1CE: add r1, sb */
    r1 = r1 + r9;
    /* 0806F1D0: ldrb r0, [r6, #1] */
    r0 = aot_read8((r6 + 1u));
    /* 0806F1D2: muls r0, r4, r0 */
    r0 = r4 * r0;
    SET_NZ(r0);
    /* 0806F1D4: lsls r0, r0, #3 */
    r0 = (r0 << 3);
    LSL_FLAGS(r0, r0, 3);
    /* 0806F1D6: add r0, ip */
    r0 = r0 + r12;
    /* 0806F1D8: str r0, [r1, #0xc] */
    aot_write32((r1 + 12u), r0);
    /* 0806F1DA: mov r5, sl */
    r5 = r10;
    /* 0806F1DC: lsls r0, r5, #0x10 */
    r0 = (r5 << 16);
    LSL_FLAGS(r0, r5, 16);
    /* 0806F1DE: lsrs r4, r0, #0x10 */
    r4 = (r0 >> 16);
    LSR_FLAGS(r4, r0, 16);
    /* 0806F1E0: ldrb r0, [r6] */
    r0 = aot_read8(r6);
    /* 0806F1E2: lsls r0, r0, #0x1c */
    r0 = (r0 << 28);
    LSL_FLAGS(r0, r0, 28);
    /* 0806F1E4: lsrs r0, r0, #0x1c */
    r0 = (r0 >> 28);
    LSR_FLAGS(r0, r0, 28);
    /* 0806F1E6: cmp r4, r0 */
    { u32 _a=r4, _b=r0, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 0806F1E8: blt #0x806f176 */
    if ((nf != vf)) goto L0806F176;
L0806F1EA:
    /* 0806F1EA: pop {r3, r4, r5} */
    r3 = aot_read32(sp + 0u);
    r4 = aot_read32(sp + 4u);
    r5 = aot_read32(sp + 8u);
    sp += 12u;
    /* 0806F1EC: mov r8, r3 */
    r8 = r3;
    /* 0806F1EE: mov sb, r4 */
    r9 = r4;
    /* 0806F1F0: mov sl, r5 */
    r10 = r5;
    /* 0806F1F2: pop {r4, r5, r6, r7} */
    r4 = aot_read32(sp + 0u);
    r5 = aot_read32(sp + 4u);
    r6 = aot_read32(sp + 8u);
    r7 = aot_read32(sp + 12u);
    sp += 16u;
    /* 0806F1F4: pop {r0} */
    r0 = aot_read32(sp + 0u);
    sp += 4u;
    /* 0806F1F6: bx r0 */
    reg[REG_PC] = r0; BAIL(reg[REG_PC]);
    AOT_RETURN();
}

/* function 0x08005ED8: 53 insns, 4 branch targets, 2 BL continuations */
static void aot_gen_08005ED8(u32 ep) {
    u32 r0 = reg[0];
    u32 r1 = reg[1];
    u32 r2 = reg[2];
    u32 r3 = reg[3];
    u32 r4 = reg[4];
    u32 r5 = reg[5];
    u32 r6 = reg[6];
    u32 r7 = reg[7];
    u32 r8 = reg[8];
    u32 r9 = reg[9];
    u32 r10 = reg[10];
    u32 r11 = reg[11];
    u32 r12 = reg[12];
    u32 sp = reg[13];
    u32 lr = reg[14];
    u32 cf = reg[REG_C_FLAG], nf = reg[REG_N_FLAG];
    u32 zf = reg[REG_Z_FLAG], vf = reg[REG_V_FLAG];
    (void)cf; (void)nf; (void)zf; (void)vf;
    switch (ep) {
    case 0x08005EFCu: goto E_08005EFC;
    case 0x08005F1Cu: goto E_08005F1C;
    default: break;  /* fall through to function head */
    }
    /* 08005ED8: push {r4, r5, r6, r7, lr} */
    sp -= 20u;
    aot_write32(sp + 0u, r4);
    aot_write32(sp + 4u, r5);
    aot_write32(sp + 8u, r6);
    aot_write32(sp + 12u, r7);
    aot_write32(sp + 16u, lr);
    /* 08005EDA: mov r7, sl */
    r7 = r10;
    /* 08005EDC: mov r6, sb */
    r6 = r9;
    /* 08005EDE: mov r5, r8 */
    r5 = r8;
    /* 08005EE0: push {r5, r6, r7} */
    sp -= 12u;
    aot_write32(sp + 0u, r5);
    aot_write32(sp + 4u, r6);
    aot_write32(sp + 8u, r7);
    /* 08005EE2: sub sp, #8 */
    sp = sp - 0x8u;
    /* 08005EE4: adds r4, r1, #0 */
    { u32 _a=r1, _b=0x0u; r4=_a+_b; ADD_FLAGS(r4,_a,_b); }
    /* 08005EE6: lsls r0, r0, #0x18 */
    r0 = (r0 << 24);
    LSL_FLAGS(r0, r0, 24);
    /* 08005EE8: lsrs r0, r0, #0x18 */
    r0 = (r0 >> 24);
    LSR_FLAGS(r0, r0, 24);
    /* 08005EEA: adds r6, r0, #0 */
    { u32 _a=r0, _b=0x0u; r6=_a+_b; ADD_FLAGS(r6,_a,_b); }
    /* 08005EEC: lsls r2, r2, #0x10 */
    r2 = (r2 << 16);
    LSL_FLAGS(r2, r2, 16);
    /* 08005EEE: lsrs r5, r2, #0x10 */
    r5 = (r2 >> 16);
    LSR_FLAGS(r5, r2, 16);
    /* 08005EF0: movs r0, #0 */
    r0 = 0x0u;
    SET_NZ(r0);
    /* 08005EF2: mov sb, r0 */
    r9 = r0;
    /* 08005EF4: movs r7, #0 */
    r7 = 0x0u;
    SET_NZ(r7);
    /* 08005EF6: adds r0, r6, #0 */
    { u32 _a=r6, _b=0x0u; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 08005EF8: bl #0x8005ea8 */
    lr = 0x8005EFDu;
    BAIL(0x08005EA8u);
E_08005EFC:
    /* 08005EFC: mov r8, r0 */
    r8 = r0;
    /* 08005EFE: cmp r0, #0 */
    { u32 _a=r0, _b=0x0u, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 08005F00: bne #0x8005f06 */
    if (!zf) goto L08005F06;
    /* 08005F02: movs r0, #0 */
    r0 = 0x0u;
    SET_NZ(r0);
    /* 08005F04: b #0x800612e */
    BAIL(0x0800612Eu);
L08005F06:
    /* 08005F06: lsls r0, r5, #0x10 */
    r0 = (r5 << 16);
    LSL_FLAGS(r0, r5, 16);
    /* 08005F08: asrs r2, r0, #0x10 */
    r2 = (u32)((s32)r0 >> 16);
    ASR_FLAGS(r2, r0, 16);
    /* 08005F0A: movs r1, #1 */
    r1 = 0x1u;
    SET_NZ(r1);
    /* 08005F0C: rsbs r1, r1, #0 */
    { u32 _a=0u, _b=r1; r1=_a-_b; SUB_FLAGS(r1,_a,_b); }
    /* 08005F0E: str r0, [sp, #4] */
    aot_write32((sp + 4u), r0);
    /* 08005F10: cmp r2, r1 */
    { u32 _a=r2, _b=r1, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 08005F12: bne #0x8005f24 */
    if (!zf) goto L08005F24;
    /* 08005F14: adds r0, r6, #0 */
    { u32 _a=r6, _b=0x0u; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 08005F16: movs r1, #2 */
    r1 = 0x2u;
    SET_NZ(r1);
    /* 08005F18: bl #0x8006378 */
    lr = 0x8005F1Du;
    BAIL(0x08006378u);
E_08005F1C:
    /* 08005F1C: lsls r0, r0, #0x18 */
    r0 = (r0 << 24);
    LSL_FLAGS(r0, r0, 24);
    /* 08005F1E: lsrs r0, r0, #0x18 */
    r0 = (r0 >> 24);
    LSR_FLAGS(r0, r0, 24);
    /* 08005F20: mov sl, r0 */
    r10 = r0;
    /* 08005F22: b #0x8005f26 */
    goto L08005F26;
L08005F24:
    /* 08005F24: mov sl, r2 */
    r10 = r2;
L08005F26:
    /* 08005F26: movs r2, #0 */
    r2 = 0x0u;
    SET_NZ(r2);
    /* 08005F28: str r2, [sp] */
    aot_write32(sp, r2);
    /* 08005F2A: movs r5, #0 */
    r5 = 0x0u;
    SET_NZ(r5);
    /* 08005F2C: movs r6, #0 */
    r6 = 0x0u;
    SET_NZ(r6);
    /* 08005F2E: b #0x800611e */
    BAIL(0x0800611Eu);
    /* 08005F30: ldrb r1, [r4] */
    r1 = aot_read8(r4);
    /* 08005F32: adds r0, r1, #0 */
    { u32 _a=r1, _b=0x0u; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 08005F34: subs r0, #0xf7 */
    { u32 _a=r0, _b=0xF7u; r0=_a-_b; SUB_FLAGS(r0,_a,_b); }
    /* 08005F36: cmp r0, #7 */
    { u32 _a=r0, _b=0x7u, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }
    /* 08005F38: bls #0x8005f3c */
    if ((!cf || zf)) goto L08005F3C;
    /* 08005F3A: b #0x80060f8 */
    BAIL(0x080060F8u);
L08005F3C:
    /* 08005F3C: lsls r0, r0, #2 */
    r0 = (r0 << 2);
    LSL_FLAGS(r0, r0, 2);
    /* 08005F3E: ldr r1, [pc, #8] */
    r1 = aot_read32(0x8005F48u);
    /* 08005F40: adds r0, r0, r1 */
    { u32 _a=r0, _b=r1; r0=_a+_b; ADD_FLAGS(r0,_a,_b); }
    /* 08005F42: ldr r0, [r0] */
    r0 = aot_read32(r0);
    /* 08005F44: mov pc, r0 */
    reg[REG_PC] = r0;
    BAIL(reg[REG_PC]);
    AOT_RETURN();
}


/* Dispatch: returns 1 if PC matched and ran AOT, 0 otherwise. */
int aot_generated_dispatch(u32 pc) {
    switch (pc) {
    case 0x08005ED8: aot_gen_08005ED8(0x08005ED8u); return 1;
    case 0x08005EFC: aot_gen_08005ED8(0x08005EFCu); return 1;
    case 0x08005F1C: aot_gen_08005ED8(0x08005F1Cu); return 1;
    case 0x0806F160: aot_gen_0806F160(0x0806F160u); return 1;
    default: return 0;
    }
}
