#!/usr/bin/env python3
"""thumb2c.py — auto-translate ARM Thumb functions to C for AOT HLE.

Reads a GBA ROM and a list of function entry PCs. For each PC,
disassembles Thumb instructions until a return is hit, translates each
insn into equivalent C operating on the gpSP `reg[]` array, and emits
one C function per ROM function plus a dispatch table.

Usage:
    tools/thumb2c.py ROM.gba 0x0806F160 0x08005ED8 ... > n64/aot_generated.c

Design:
- Each translated function takes no args, reads/writes the global reg[]
  and GBA memory via aot_read*/aot_write* helpers.
- Function entry: snapshot r0..r12, sp, lr into local C variables.
- Function exit (POP {pc}, BX lr): write back, set PC=LR, return.
- Internal branches: emit a `Lxxxx:` label at every branch target,
  use `goto Lxxxx;` for branches.
- BL: if target is in known-AOT set, call its entry; else BAIL
  (write back state, set PC to BL site, return — interpreter resumes).
- Unsupported insn: BAIL with the same convention.

This file emits C that #include's "../common.h", "../cpu.h",
"../gba_memory.h" and the existing aot_read/write helpers from aot_hle.c.
"""
import sys
import os
import struct
import argparse
from capstone import Cs, CS_ARCH_ARM, CS_MODE_THUMB, CsError
from capstone.arm import (
    ARM_OP_IMM, ARM_OP_REG, ARM_OP_MEM,
    ARM_REG_R0, ARM_REG_R12, ARM_REG_SP, ARM_REG_LR, ARM_REG_PC,
)

ROM_BASE = 0x08000000

# Thumb mnemonics we know how to translate. Anything else triggers BAIL.
SUPPORTED = {
    'mov', 'movs', 'mvn', 'mvns',
    'add', 'adds', 'sub', 'subs',
    'and', 'ands', 'orr', 'orrs', 'eor', 'eors', 'bic', 'bics',
    'lsl', 'lsls', 'lsr', 'lsrs', 'asr', 'asrs', 'ror', 'rors',
    'mul', 'muls', 'cmp', 'cmn', 'tst', 'neg', 'negs',
    'ldr', 'ldrh', 'ldrb', 'ldrsh', 'ldrsb',
    'str', 'strh', 'strb',
    'push', 'pop',
    'b', 'bl', 'bx', 'blx',
    'nop',
}

# Branch / control-flow mnemonics
COND_BRANCH = {
    'beq','bne','bcs','bhs','bcc','blo','bmi','bpl','bvs','bvc',
    'bhi','bls','bge','blt','bgt','ble',
}
UNCOND_BRANCH = {'b'}
RETURN_INSNS = {'pop_pc', 'bx_lr', 'bx_pc'}  # synthetic markers


def reg_name(cs_reg):
    """Map a capstone reg id to a C variable name (r0..r12, sp, lr, pc)."""
    if ARM_REG_R0 <= cs_reg <= ARM_REG_R12:
        return f"r{cs_reg - ARM_REG_R0}"
    if cs_reg == ARM_REG_SP:
        return "sp"
    if cs_reg == ARM_REG_LR:
        return "lr"
    if cs_reg == ARM_REG_PC:
        return "pc"
    return None


def reg_idx(cs_reg):
    """Map a capstone reg id to gpSP `reg[]` index, or None if special."""
    if ARM_REG_R0 <= cs_reg <= ARM_REG_R12:
        return cs_reg - ARM_REG_R0
    if cs_reg == ARM_REG_SP:
        return 13
    if cs_reg == ARM_REG_LR:
        return 14
    if cs_reg == ARM_REG_PC:
        return 15
    return None


def load_rom(path):
    with open(path, 'rb') as f:
        return f.read()


def make_disasm():
    md = Cs(CS_ARCH_ARM, CS_MODE_THUMB)
    md.detail = True
    return md


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('rom', help='GBA ROM path')
    ap.add_argument('pcs', nargs='*', help='function entry PCs (hex)')
    ap.add_argument('--pcs-from', help='read PCs from file (one hex per line)')
    ap.add_argument('-o', '--output', help='output .c file (default stdout)')
    ap.add_argument('--exclude', action='append', default=[],
                    help='hex PCs to skip (e.g. those covered by hand-written AOT)')
    args = ap.parse_args()
    excluded = {int(x, 0) & ~1 for x in args.exclude}
    pc_strs = list(args.pcs)
    if args.pcs_from:
        with open(args.pcs_from) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    pc_strs.append(line)

    rom = load_rom(args.rom)
    md = make_disasm()
    raw_targets = [int(pc, 0) & ~1 for pc in pc_strs]
    # De-dupe and exclude
    seen = set()
    targets = []
    for pc in raw_targets:
        if pc in seen or pc in excluded:
            continue
        seen.add(pc)
        targets.append(pc)
    target_set = set(targets)

    out = open(args.output, 'w') if args.output else sys.stdout
    emit_header(out, targets)
    entry_to_func = {}
    for pc in targets:
        entries = translate_function(out, rom, md, pc, target_set)
        if entries is None:
            continue
        for ep in entries:
            entry_to_func[ep] = pc
    emit_dispatch(out, entry_to_func)
    emit_page_bitmap(out, entry_to_func.keys())
    if args.output:
        out.close()


HEADER_TEMPLATE = r"""/* AUTO-GENERATED by tools/thumb2c.py — do not edit. */
#include "../common.h"
#include "../cpu.h"
#include "../gba_memory.h"

extern u32 aot_read32(u32);
extern u16 aot_read16(u32);
extern u8  aot_read8 (u32);
extern void aot_write32(u32, u32);
extern void aot_write16(u32, u16);
extern void aot_write8 (u32, u8);

/* Flag computation helpers — match ARM7TDMI semantics. */
#define SET_NZ(x) do { u32 _x=(u32)(x); nf=(_x>>31)&1u; zf=(_x==0); } while(0)
#define ADD_FLAGS(d,a,b) do { u32 _a=(a),_b=(b),_d=(d); \
    nf=(_d>>31)&1u; zf=(_d==0); \
    cf=(_d<_a); \
    vf=(((_a^_d)&(_b^_d))>>31)&1u; } while(0)
#define SUB_FLAGS(d,a,b) do { u32 _a=(a),_b=(b),_d=(d); \
    nf=(_d>>31)&1u; zf=(_d==0); \
    cf=(_a>=_b); \
    vf=(((_a^_b)&(_a^_d))>>31)&1u; } while(0)
#define LSL_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(32-_n))&1u; \
    SET_NZ(d); } while(0)
#define LSR_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(_n-1))&1u; \
    SET_NZ(d); } while(0)
#define ASR_FLAGS(d,a,n) do { u32 _n=(n); \
    if (_n) cf=((u32)(a)>>(_n-1))&1u; \
    SET_NZ(d); } while(0)

/* BAIL: write all state back, set PC to bail addr (assumed Thumb,
 * since we never bail mid-function across a mode switch), return so
 * the interpreter can resume. */
#define BAIL(addr) do { \
    reg[0]=r0; reg[1]=r1; reg[2]=r2; reg[3]=r3; \
    reg[4]=r4; reg[5]=r5; reg[6]=r6; reg[7]=r7; \
    reg[8]=r8; reg[9]=r9; reg[10]=r10; reg[11]=r11; reg[12]=r12; \
    reg[13]=sp; reg[14]=lr; reg[REG_PC]=(addr); \
    reg[REG_C_FLAG]=cf; reg[REG_N_FLAG]=nf; \
    reg[REG_Z_FLAG]=zf; reg[REG_V_FLAG]=vf; \
    return; \
} while(0)

/* Indirect-branch BAIL: target's low bit selects mode (1=Thumb,
 * 0=ARM).  Used for BX/BLX-reg/POP{pc}/MOV pc,X and the function
 * return AOT_RETURN. */
#define BAIL_INDIRECT(target) do { \
    u32 _t = (target); \
    reg[0]=r0; reg[1]=r1; reg[2]=r2; reg[3]=r3; \
    reg[4]=r4; reg[5]=r5; reg[6]=r6; reg[7]=r7; \
    reg[8]=r8; reg[9]=r9; reg[10]=r10; reg[11]=r11; reg[12]=r12; \
    reg[13]=sp; reg[14]=lr; \
    if (_t & 1u) { reg[REG_PC]=_t & ~1u; reg[REG_CPSR] |= 0x20u; } \
    else         { reg[REG_PC]=_t;        reg[REG_CPSR] &= ~0x20u; } \
    reg[REG_C_FLAG]=cf; reg[REG_N_FLAG]=nf; \
    reg[REG_Z_FLAG]=zf; reg[REG_V_FLAG]=vf; \
    return; \
} while(0)

#define AOT_RETURN() BAIL_INDIRECT(lr)

"""


def emit_header(out, targets):
    out.write(HEADER_TEMPLATE)


def emit_dispatch(out, entry_to_func):
    out.write('\n/* Dispatch: returns 1 if PC matched and ran AOT, 0 otherwise. */\n')
    out.write('int aot_generated_dispatch(u32 pc) {\n')
    out.write('    switch (pc) {\n')
    for ep in sorted(entry_to_func):
        fn = entry_to_func[ep]
        out.write(f'    case 0x{ep:08X}: aot_gen_{fn:08X}(0x{ep:08X}u); return 1;\n')
    out.write('    default: return 0;\n')
    out.write('    }\n')
    out.write('}\n')


def emit_page_bitmap(out, entries):
    """Emit a 4KB-page bitmap: 1 bit per page in the GBA address space.
    cpu.cc uses this for a zero-overhead fast-reject — the bitmap is
    only ~1KB and fits comfortably in D-cache, so the inline check is
    just a load + shift + and + branch (predicted not-taken).

    Indexed by `(pc >> 12) & 0x1FFF` — covers full 32MB ROM region
    without bounds checks. Hash collisions with non-ROM PCs (e.g.
    EWRAM/IWRAM) are harmless: the dispatch returns 0 on a non-match.
    """
    bitmap = [0] * 256  # 256 u32s × 32 bits = 8192 page slots
    for pc in entries:
        page_idx = (pc >> 12) & 0x1FFF
        bitmap[page_idx >> 5] |= 1 << (page_idx & 31)
    out.write('\n/* Page-presence bitmap (4KB-page granularity) for fast '
              'reject in cpu.cc. */\n')
    out.write('const u32 aot_page_bitmap[256] = {\n')
    for i in range(0, 256, 8):
        row = ', '.join(f'0x{bitmap[j]:08X}u' for j in range(i, i + 8))
        out.write(f'    {row},\n')
    out.write('};\n')


MAX_FN_BYTES = 4096   # safety cap; bail if no return seen by then


def disasm_function(rom, md, pc):
    """Disassemble a Thumb function starting at `pc` (ROM address).

    Returns a list of capstone insns from `pc` until we hit a return
    (POP {..., pc}, BX lr, or unconditional B with no fall-through past
    the function bound). Bail if MAX_FN_BYTES exceeded.
    """
    off = pc - ROM_BASE
    if off < 0 or off >= len(rom):
        return None, f"PC 0x{pc:08X} outside ROM"

    end = min(off + MAX_FN_BYTES, len(rom))
    insns = []
    seen_return = False
    branch_targets = set()
    cur = off

    # We disassemble linearly; a function ends when we encounter a
    # terminator (POP {pc} / BX) AND there are no pending forward
    # branches into addresses past it. To keep the first version
    # simple, we stop at the *first* terminator that has no forward
    # branch target beyond it.
    max_branch_target = pc

    while cur < end:
        chunk = rom[cur:cur + 4]
        try:
            decoded = list(md.disasm(chunk, ROM_BASE + cur, count=1))
        except CsError:
            decoded = []
        if not decoded:
            return None, f"undecodable at 0x{ROM_BASE + cur:08X}"
        ins = decoded[0]
        insns.append(ins)
        cur += ins.size

        m = ins.mnemonic.lower()

        # Track branch targets within the function for label generation.
        if m in COND_BRANCH or m in UNCOND_BRANCH:
            if ins.operands and ins.operands[0].type == ARM_OP_IMM:
                tgt = ins.operands[0].imm
                branch_targets.add(tgt)
                if tgt > max_branch_target:
                    max_branch_target = tgt

        # Detect terminators. Two flavors:
        # - "soft" (POP {pc}, BX, unconditional B): only terminate if
        #   we're past the last forward branch target. There may be
        #   multiple exits scattered through the function.
        # - "hard" (MOV pc, X / ADD pc, X): a switch-table dispatch
        #   followed by a literal pool. Disassembling further would
        #   produce garbage. Always terminate.
        is_soft_terminator = False
        is_hard_terminator = False
        if m == 'pop':
            for op in ins.operands:
                if op.type == ARM_OP_REG and op.reg == ARM_REG_PC:
                    is_soft_terminator = True
                    break
        elif m == 'bx':
            is_soft_terminator = True
        elif m in ('mov', 'add') and ins.operands and \
                ins.operands[0].type == ARM_OP_REG and \
                ins.operands[0].reg == ARM_REG_PC:
            is_hard_terminator = True
        elif m in UNCOND_BRANCH:
            cur_pc = ROM_BASE + cur
            if cur_pc > max_branch_target:
                is_soft_terminator = True

        if is_hard_terminator:
            seen_return = True
            break
        if is_soft_terminator:
            cur_pc = ROM_BASE + cur
            if cur_pc > max_branch_target:
                seen_return = True
                break

    if not seen_return:
        return None, f"no terminator found within {MAX_FN_BYTES} bytes"
    return (insns, branch_targets), None


# ----- operand helpers ---------------------------------------------------

def op_reg_name(op):
    """Return C variable name for a register operand, or None if unsupported."""
    if op.type != ARM_OP_REG:
        return None
    return reg_name(op.reg)


def op_imm(op):
    return op.imm if op.type == ARM_OP_IMM else None


def op_mem(op):
    """Return (base_name, index_name_or_None, disp_int) for a [mem] operand."""
    if op.type != ARM_OP_MEM:
        return None
    base = reg_name(op.mem.base) if op.mem.base else None
    idx = reg_name(op.mem.index) if op.mem.index else None
    return (base, idx, op.mem.disp)


# ----- per-mnemonic translators ------------------------------------------
# Each returns a list of C statement strings (without leading indent), or
# None to signal "not handled, please BAIL". `addr` is the insn PC,
# `next_addr` is addr + ins.size.

def t_nop(ins, addr, next_addr, ctx):
    return [';']


def t_mov(ins, addr, next_addr, ctx):
    """MOV / MOVS — register or immediate. No operand-2 shifts in Thumb-1."""
    setflags = ins.mnemonic.lower() == 'movs'
    ops = ins.operands
    if len(ops) != 2:
        return None
    rd = op_reg_name(ops[0])
    if rd is None:
        return None
    # Indirect branch: mov pc, X — bit 0 of source selects mode
    if rd == 'pc':
        if ops[1].type == ARM_OP_REG:
            rs = op_reg_name(ops[1])
            if rs is None:
                return None
            return [f'BAIL_INDIRECT({rs});']
        if ops[1].type == ARM_OP_IMM:
            return [f'BAIL_INDIRECT(0x{ops[1].imm:X}u);']
        return None
    if ops[1].type == ARM_OP_IMM:
        imm = ops[1].imm
        if setflags:
            return [f'{rd} = 0x{imm:X}u;', f'SET_NZ({rd});']
        return [f'{rd} = 0x{imm:X}u;']
    if ops[1].type == ARM_OP_REG:
        rs = op_reg_name(ops[1])
        if rs is None:
            return None
        if setflags:
            return [f'{rd} = {rs};', f'SET_NZ({rd});']
        return [f'{rd} = {rs};']
    return None


def t_add(ins, addr, next_addr, ctx):
    setflags = ins.mnemonic.lower() == 'adds'
    ops = ins.operands
    # Forms: add Rd, Rn, Rm | add Rd, Rn, #imm | add Rd, #imm | add Rd, Rs
    # Special: add Rd, pc, #imm (PC-relative) | add Rd, sp, #imm
    if len(ops) == 3:
        rd = op_reg_name(ops[0])
        rn = op_reg_name(ops[1])
        if rd is None or rn is None:
            return None
        if rn == 'pc':
            # PC-rel: in Thumb, PC reads as (insn + 4) & ~3
            base = (addr + 4) & ~3
            imm = op_imm(ops[2])
            if imm is None:
                return None
            return [f'{rd} = 0x{(base + imm) & 0xFFFFFFFF:X}u;']
        if ops[2].type == ARM_OP_IMM:
            imm = ops[2].imm
            if setflags:
                return [f'{{ u32 _a={rn}, _b=0x{imm:X}u; '
                        f'{rd}=_a+_b; ADD_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rn} + 0x{imm:X}u;']
        if ops[2].type == ARM_OP_REG:
            rm = op_reg_name(ops[2])
            if rm is None:
                return None
            if setflags:
                return [f'{{ u32 _a={rn}, _b={rm}; '
                        f'{rd}=_a+_b; ADD_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rn} + {rm};']
    if len(ops) == 2:
        rd = op_reg_name(ops[0])
        if rd is None:
            return None
        if ops[1].type == ARM_OP_IMM:
            imm = ops[1].imm
            if setflags:
                return [f'{{ u32 _a={rd}, _b=0x{imm:X}u; '
                        f'{rd}=_a+_b; ADD_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rd} + 0x{imm:X}u;']
        if ops[1].type == ARM_OP_REG:
            rs = op_reg_name(ops[1])
            if rs is None:
                return None
            # Hi-reg add: never sets flags
            return [f'{rd} = {rd} + {rs};']
    return None


def t_sub(ins, addr, next_addr, ctx):
    setflags = ins.mnemonic.lower() == 'subs'
    ops = ins.operands
    if len(ops) == 3:
        rd = op_reg_name(ops[0])
        rn = op_reg_name(ops[1])
        if rd is None or rn is None:
            return None
        if ops[2].type == ARM_OP_IMM:
            imm = ops[2].imm
            if setflags:
                return [f'{{ u32 _a={rn}, _b=0x{imm:X}u; '
                        f'{rd}=_a-_b; SUB_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rn} - 0x{imm:X}u;']
        if ops[2].type == ARM_OP_REG:
            rm = op_reg_name(ops[2])
            if rm is None:
                return None
            if setflags:
                return [f'{{ u32 _a={rn}, _b={rm}; '
                        f'{rd}=_a-_b; SUB_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rn} - {rm};']
    if len(ops) == 2:
        rd = op_reg_name(ops[0])
        if rd is None:
            return None
        if ops[1].type == ARM_OP_IMM:
            imm = ops[1].imm
            if setflags:
                return [f'{{ u32 _a={rd}, _b=0x{imm:X}u; '
                        f'{rd}=_a-_b; SUB_FLAGS({rd},_a,_b); }}']
            return [f'{rd} = {rd} - 0x{imm:X}u;']
    return None


def t_push(ins, addr, next_addr, ctx):
    """PUSH {regs} — decrement sp, store regs in ascending order."""
    regs = []
    for op in ins.operands:
        if op.type != ARM_OP_REG:
            return None
        nm = reg_name(op.reg)
        if nm is None:
            return None
        regs.append(nm)
    # ARM ABI: lowest reg at lowest address. Capstone lists regs in
    # numerical order already.
    lines = [f'sp -= {len(regs) * 4}u;']
    for i, r in enumerate(regs):
        lines.append(f'aot_write32(sp + {i * 4}u, {r});')
    return lines


def t_pop(ins, addr, next_addr, ctx):
    regs = []
    pop_pc = False
    for op in ins.operands:
        if op.type != ARM_OP_REG:
            return None
        if op.reg == ARM_REG_PC:
            pop_pc = True
            continue
        nm = reg_name(op.reg)
        if nm is None:
            return None
        regs.append(nm)
    # Stack layout: lowest reg at lowest address; PC last.
    lines = []
    for i, r in enumerate(regs):
        lines.append(f'{r} = aot_read32(sp + {i * 4}u);')
    if pop_pc:
        # POP {pc} = function return. lr := stacked PC, then return.
        lines.append(f'lr = aot_read32(sp + {len(regs) * 4}u);')
        lines.append(f'sp += {(len(regs) + 1) * 4}u;')
        lines.append('AOT_RETURN();')
    else:
        lines.append(f'sp += {len(regs) * 4}u;')
    return lines


def t_b(ins, addr, next_addr, ctx):
    """Unconditional B — goto label inside function, else BAIL."""
    if not ins.operands or ins.operands[0].type != ARM_OP_IMM:
        return None
    tgt = ins.operands[0].imm
    if tgt in ctx['branch_targets']:
        return [f'goto L{tgt:08X};']
    return [f'BAIL(0x{tgt:08X}u);']


def t_bcond(ins, addr, next_addr, ctx):
    """Conditional branch — emit C if() goto."""
    if not ins.operands or ins.operands[0].type != ARM_OP_IMM:
        return None
    tgt = ins.operands[0].imm
    cond_map = {
        'beq': 'zf', 'bne': '!zf',
        'bcs': 'cf', 'bhs': 'cf',
        'bcc': '!cf', 'blo': '!cf',
        'bmi': 'nf', 'bpl': '!nf',
        'bvs': 'vf', 'bvc': '!vf',
        'bhi': '(cf && !zf)', 'bls': '(!cf || zf)',
        'bge': '(nf == vf)', 'blt': '(nf != vf)',
        'bgt': '(!zf && nf == vf)', 'ble': '(zf || nf != vf)',
    }
    cond = cond_map.get(ins.mnemonic.lower())
    if cond is None:
        return None
    if tgt in ctx['branch_targets']:
        return [f'if ({cond}) goto L{tgt:08X};']
    # Branch out of function — BAIL with PC=tgt only when condition holds.
    return [f'if ({cond}) BAIL(0x{tgt:08X}u);']


def t_bl(ins, addr, next_addr, ctx):
    """BL — call. Set lr=continuation|1, BAIL to target. The dispatch
    table includes the continuation address so we re-enter this same
    function at a label after the called function returns."""
    if not ins.operands or ins.operands[0].type != ARM_OP_IMM:
        return None
    tgt = ins.operands[0].imm
    cont = next_addr
    ctx['continuations'].add(cont)
    return [
        f'lr = 0x{(cont | 1) & 0xFFFFFFFF:X}u;',
        f'BAIL(0x{tgt:08X}u);',
    ]


def t_blx(ins, addr, next_addr, ctx):
    """BLX — like BL but target is a register; bit 0 selects mode."""
    ops = ins.operands
    if len(ops) != 1:
        return None
    cont = next_addr
    ctx['continuations'].add(cont)
    if ops[0].type == ARM_OP_REG:
        rm = reg_name(ops[0].reg)
        if rm is None:
            return None
        return [
            f'lr = 0x{(cont | 1) & 0xFFFFFFFF:X}u;',
            f'BAIL_INDIRECT({rm});',
        ]
    if ops[0].type == ARM_OP_IMM:
        tgt = ops[0].imm
        # BLX immediate (Thumb-1) targets ARM mode — clear bit 0.
        return [
            f'lr = 0x{(cont | 1) & 0xFFFFFFFF:X}u;',
            f'BAIL_INDIRECT(0x{tgt & ~1:08X}u);',
        ]
    return None


def t_bx(ins, addr, next_addr, ctx):
    """BX Rm — branch w/ mode switch. Bit 0 of Rm selects ARM/Thumb.
    BX lr is a typical function return."""
    if not ins.operands or ins.operands[0].type != ARM_OP_REG:
        return None
    nm = reg_name(ins.operands[0].reg)
    if nm is None:
        return None
    if nm == 'lr':
        return ['AOT_RETURN();']
    return [f'BAIL_INDIRECT({nm});']


# ----- dispatch ----------------------------------------------------------

# ----- shifts ------------------------------------------------------------

def _t_shift(ins, addr, next_addr, ctx, op_c, flag_macro):
    """Generic shift: lsl/lsr/asr, with optional setflags suffix.

    Forms:
       SHIFT Rd, Rs, #imm
       SHIFT Rd, Rs            (shift Rd by Rs)
       SHIFTS Rd, Rs           (same, with flags)
    """
    setflags = ins.mnemonic.lower().endswith('s')
    ops = ins.operands
    if len(ops) == 3:
        rd = op_reg_name(ops[0])
        rs = op_reg_name(ops[1])
        if rd is None or rs is None:
            return None
        if ops[2].type == ARM_OP_IMM:
            imm = ops[2].imm
            # Special: LSR #0 / ASR #0 in Thumb-1 mean shift-by-32.
            # Capstone normalises this to 32 already in op.imm.
            if imm == 0 and op_c == '<<':
                # LSL #0 = MOV (no flag change for C)
                if setflags:
                    return [f'{rd} = {rs};', f'SET_NZ({rd});']
                return [f'{rd} = {rs};']
            if imm == 32 and op_c == '<<':
                # Not encodable; treat as zero result.
                if setflags:
                    return [f'cf = {rs} & 1u;', f'{rd} = 0u;', f'SET_NZ({rd});']
                return [f'{rd} = 0u;']
            if op_c == '>>>':  # ASR
                expr = f'(u32)((s32){rs} >> {imm})'
            else:
                expr = f'({rs} {op_c} {imm})'
            if setflags:
                return [f'{rd} = {expr};',
                        f'{flag_macro}({rd}, {rs}, {imm});']
            return [f'{rd} = {expr};']
        if ops[2].type == ARM_OP_REG:
            rm = op_reg_name(ops[2])
            if rm is None:
                return None
            # Variable shift: only low byte of Rm is used.
            if op_c == '>>>':
                expr = f'({rm} & 0xFFu) >= 32 ? ((s32){rs} >> 31) : ((s32){rs} >> ({rm} & 0xFFu))'
                expr = f'(u32)({expr})'
            else:
                expr = f'({rm} & 0xFFu) >= 32 ? 0u : ({rs} {op_c} ({rm} & 0xFFu))'
            if setflags:
                return [f'{rd} = ({expr});',
                        f'SET_NZ({rd});  /* note: cf approximation */']
            return [f'{rd} = ({expr});']
    if len(ops) == 2:
        rd = op_reg_name(ops[0])
        rm = op_reg_name(ops[1])
        if rd is None or rm is None:
            return None
        if op_c == '>>>':
            expr = f'({rm} & 0xFFu) >= 32 ? ((s32){rd} >> 31) : ((s32){rd} >> ({rm} & 0xFFu))'
            expr = f'(u32)({expr})'
        else:
            expr = f'({rm} & 0xFFu) >= 32 ? 0u : ({rd} {op_c} ({rm} & 0xFFu))'
        if setflags:
            return [f'{rd} = ({expr});', f'SET_NZ({rd});']
        return [f'{rd} = ({expr});']
    return None


def t_lsl(ins, addr, n, ctx): return _t_shift(ins, addr, n, ctx, '<<', 'LSL_FLAGS')
def t_lsr(ins, addr, n, ctx): return _t_shift(ins, addr, n, ctx, '>>', 'LSR_FLAGS')
def t_asr(ins, addr, n, ctx): return _t_shift(ins, addr, n, ctx, '>>>', 'ASR_FLAGS')


# ----- ALU register ops --------------------------------------------------

def _t_alu(ins, addr, next_addr, ctx, op_c, setflags_default):
    """Generic 2-operand ALU: AND/ORR/EOR/BIC. Always sets flags in Thumb-1."""
    setflags = ins.mnemonic.lower().endswith('s') or setflags_default
    ops = ins.operands
    if len(ops) != 2:
        return None
    rd = op_reg_name(ops[0])
    rm = op_reg_name(ops[1])
    if rd is None or rm is None:
        return None
    if op_c == '&~':
        expr = f'({rd} & ~{rm})'
    else:
        expr = f'({rd} {op_c} {rm})'
    if setflags:
        return [f'{rd} = {expr};', f'SET_NZ({rd});']
    return [f'{rd} = {expr};']


def t_and(ins, a, n, c): return _t_alu(ins, a, n, c, '&', True)
def t_orr(ins, a, n, c): return _t_alu(ins, a, n, c, '|', True)
def t_eor(ins, a, n, c): return _t_alu(ins, a, n, c, '^', True)
def t_bic(ins, a, n, c): return _t_alu(ins, a, n, c, '&~', True)


def t_mvn(ins, addr, next_addr, ctx):
    setflags = ins.mnemonic.lower().endswith('s')
    ops = ins.operands
    if len(ops) != 2:
        return None
    rd = op_reg_name(ops[0])
    rm = op_reg_name(ops[1])
    if rd is None or rm is None:
        return None
    if setflags:
        return [f'{rd} = ~{rm};', f'SET_NZ({rd});']
    return [f'{rd} = ~{rm};']


def t_neg(ins, addr, next_addr, ctx):
    """NEG/NEGS/RSB/RSBS Rd, Rm[, #0] — Rd = 0 - Rm, sets flags."""
    ops = ins.operands
    if len(ops) < 2 or len(ops) > 3:
        return None
    rd = op_reg_name(ops[0])
    rm = op_reg_name(ops[1])
    if rd is None or rm is None:
        return None
    if len(ops) == 3:
        # RSB form: ops[2] should be #0 in Thumb-1
        if ops[2].type != ARM_OP_IMM or ops[2].imm != 0:
            return None
    return [f'{{ u32 _a=0u, _b={rm}; {rd}=_a-_b; SUB_FLAGS({rd},_a,_b); }}']


def t_mul(ins, addr, next_addr, ctx):
    setflags = ins.mnemonic.lower().endswith('s')
    ops = ins.operands
    # MUL Rd, Rm or MUL Rd, Rm, Rs
    if len(ops) == 2:
        rd = op_reg_name(ops[0])
        rm = op_reg_name(ops[1])
        if rd is None or rm is None:
            return None
        if setflags:
            return [f'{rd} = {rd} * {rm};', f'SET_NZ({rd});']
        return [f'{rd} = {rd} * {rm};']
    if len(ops) == 3:
        rd = op_reg_name(ops[0])
        rm = op_reg_name(ops[1])
        rs = op_reg_name(ops[2])
        if rd is None or rm is None or rs is None:
            return None
        if setflags:
            return [f'{rd} = {rm} * {rs};', f'SET_NZ({rd});']
        return [f'{rd} = {rm} * {rs};']
    return None


def t_cmp(ins, addr, next_addr, ctx):
    ops = ins.operands
    if len(ops) != 2:
        return None
    a = op_reg_name(ops[0])
    if a is None:
        return None
    if ops[1].type == ARM_OP_IMM:
        b = f'0x{ops[1].imm:X}u'
    elif ops[1].type == ARM_OP_REG:
        b = op_reg_name(ops[1])
        if b is None:
            return None
    else:
        return None
    return [f'{{ u32 _a={a}, _b={b}, _d=_a-_b; SUB_FLAGS(_d,_a,_b); }}']


def t_cmn(ins, addr, next_addr, ctx):
    ops = ins.operands
    if len(ops) != 2:
        return None
    a = op_reg_name(ops[0])
    if a is None:
        return None
    if ops[1].type == ARM_OP_REG:
        b = op_reg_name(ops[1])
    elif ops[1].type == ARM_OP_IMM:
        b = f'0x{ops[1].imm:X}u'
    else:
        return None
    if b is None:
        return None
    return [f'{{ u32 _a={a}, _b={b}, _d=_a+_b; ADD_FLAGS(_d,_a,_b); }}']


def t_tst(ins, addr, next_addr, ctx):
    ops = ins.operands
    if len(ops) != 2:
        return None
    a = op_reg_name(ops[0])
    b = op_reg_name(ops[1])
    if a is None or b is None:
        return None
    return [f'SET_NZ({a} & {b});']


# ----- memory loads / stores --------------------------------------------

def _mem_addr(rd, mem, addr):
    """Build C expression for the effective address of a [mem] operand."""
    base, idx, disp = mem
    # PC-relative: in Thumb LDR Rd, [pc, #imm], PC is (insn+4) & ~3
    if base == 'pc':
        eff = (addr + 4) & ~3
        return f'0x{(eff + disp) & 0xFFFFFFFF:X}u'
    if idx:
        if disp:
            return f'({base} + {idx} + {disp})'
        return f'({base} + {idx})'
    if disp:
        return f'({base} + {disp}u)'
    return f'{base}'


def _t_load(ins, addr, next_addr, ctx, c_read, sign_ext_to=None):
    ops = ins.operands
    if len(ops) != 2:
        return None
    rd = op_reg_name(ops[0])
    if rd is None:
        return None
    mem = op_mem(ops[1])
    if mem is None or mem[0] is None:
        return None
    ea = _mem_addr(rd, mem, addr)
    if sign_ext_to == 16:
        return [f'{rd} = (u32)(s32)(s16){c_read}({ea});']
    if sign_ext_to == 8:
        return [f'{rd} = (u32)(s32)(s8){c_read}({ea});']
    return [f'{rd} = {c_read}({ea});']


def t_ldr(ins, a, n, c):  return _t_load(ins, a, n, c, 'aot_read32')
def t_ldrh(ins, a, n, c): return _t_load(ins, a, n, c, 'aot_read16')
def t_ldrb(ins, a, n, c): return _t_load(ins, a, n, c, 'aot_read8')
def t_ldrsh(ins, a, n, c): return _t_load(ins, a, n, c, 'aot_read16', 16)
def t_ldrsb(ins, a, n, c): return _t_load(ins, a, n, c, 'aot_read8', 8)


def _t_store(ins, addr, next_addr, ctx, c_write):
    ops = ins.operands
    if len(ops) != 2:
        return None
    rd = op_reg_name(ops[0])
    if rd is None:
        return None
    mem = op_mem(ops[1])
    if mem is None or mem[0] is None or mem[0] == 'pc':
        return None
    ea = _mem_addr(rd, mem, addr)
    return [f'{c_write}({ea}, {rd});']


def t_str(ins, a, n, c):  return _t_store(ins, a, n, c, 'aot_write32')
def t_strh(ins, a, n, c): return _t_store(ins, a, n, c, 'aot_write16')
def t_strb(ins, a, n, c): return _t_store(ins, a, n, c, 'aot_write8')


# ----- LDM / STM (small subset: post-increment Rb! with low regs) -------

def t_ldm(ins, addr, next_addr, ctx):
    ops = ins.operands
    if len(ops) < 2:
        return None
    base = op_reg_name(ops[0])
    if base is None:
        return None
    regs = []
    for op in ops[1:]:
        if op.type != ARM_OP_REG:
            return None
        nm = reg_name(op.reg)
        if nm is None:
            return None
        regs.append(nm)
    lines = []
    for i, r in enumerate(regs):
        lines.append(f'{r} = aot_read32({base} + {i * 4}u);')
    if ins.writeback or '!' in ins.op_str:
        lines.append(f'{base} += {len(regs) * 4}u;')
    return lines


def t_stm(ins, addr, next_addr, ctx):
    ops = ins.operands
    if len(ops) < 2:
        return None
    base = op_reg_name(ops[0])
    if base is None:
        return None
    regs = []
    for op in ops[1:]:
        if op.type != ARM_OP_REG:
            return None
        nm = reg_name(op.reg)
        if nm is None:
            return None
        regs.append(nm)
    lines = []
    for i, r in enumerate(regs):
        lines.append(f'aot_write32({base} + {i * 4}u, {r});')
    if ins.writeback or '!' in ins.op_str:
        lines.append(f'{base} += {len(regs) * 4}u;')
    return lines


TRANSLATORS = {
    'nop':  t_nop,
    'mov':  t_mov, 'movs': t_mov, 'mvn': t_mvn, 'mvns': t_mvn,
    'add':  t_add, 'adds': t_add,
    'sub':  t_sub, 'subs': t_sub,
    'push': t_push, 'pop': t_pop,
    'b':    t_b, 'bx': t_bx,
    'lsl':  t_lsl, 'lsls': t_lsl,
    'lsr':  t_lsr, 'lsrs': t_lsr,
    'asr':  t_asr, 'asrs': t_asr,
    'and':  t_and, 'ands': t_and,
    'orr':  t_orr, 'orrs': t_orr,
    'eor':  t_eor, 'eors': t_eor,
    'bic':  t_bic, 'bics': t_bic,
    'mul':  t_mul, 'muls': t_mul,
    'neg':  t_neg, 'negs': t_neg,
    'rsb':  t_neg, 'rsbs': t_neg,
    'bl':   t_bl,  'blx':  t_blx,
    'cmp':  t_cmp, 'cmn':  t_cmn, 'tst': t_tst,
    'ldr':  t_ldr, 'ldrh': t_ldrh, 'ldrb': t_ldrb,
    'ldrsh': t_ldrsh, 'ldrsb': t_ldrsb,
    'str':  t_str, 'strh': t_strh, 'strb': t_strb,
    'ldm':  t_ldm, 'ldmia': t_ldm,
    'stm':  t_stm, 'stmia': t_stm,
}
for cb in COND_BRANCH:
    TRANSLATORS[cb] = t_bcond


def translate_insn(ins, ctx):
    m = ins.mnemonic.lower()
    fn = TRANSLATORS.get(m)
    if fn is None:
        return None
    next_addr = ins.address + ins.size
    return fn(ins, ins.address, next_addr, ctx)


def translate_function(out, rom, md, pc, target_set):
    res, err = disasm_function(rom, md, pc)
    if err:
        # Skip entirely — don't register in dispatch table.
        out.write(f'/* SKIP 0x{pc:08X}: {err} */\n')
        return None

    insns, branch_targets = res
    insn_addrs = {ins.address for ins in insns}
    # Filter branch_targets to only those we actually emit. Anything
    # else needs a BAIL (the target is outside the AOT function).
    branch_targets = branch_targets & insn_addrs
    ctx = {
        'branch_targets': branch_targets,
        'insn_addrs': insn_addrs,
        'aot_targets': target_set,
        'continuations': set(),
    }
    skipped = []

    # Pre-pass: translate all instructions so we know the continuations.
    body_lines = []
    for ins in insns:
        if ins.address in branch_targets:
            body_lines.append(('label', f'L{ins.address:08X}:'))
        body_lines.append(('comment',
            f'/* {ins.address:08X}: {ins.mnemonic} {ins.op_str} */'))
        lines = translate_insn(ins, ctx)
        if lines is None:
            skipped.append((ins.address, ins.mnemonic, ins.op_str))
            body_lines.append(('stmt',
                f'BAIL(0x{ins.address:08X}u); /* unsupported: '
                f'{ins.mnemonic} {ins.op_str} */'))
        else:
            for l in lines:
                body_lines.append(('stmt', l))
        # After this insn, if next addr is a continuation, mark it as
        # such so we emit an entry label (E_xxx) right at it.

    out.write(f'/* function 0x{pc:08X}: {len(insns)} insns, '
              f'{len(branch_targets)} branch targets, '
              f'{len(ctx["continuations"])} BL continuations */\n')
    out.write(f'static void aot_gen_{pc:08X}(u32 ep) {{\n')
    for i in range(13):
        out.write(f'    u32 r{i} = reg[{i}];\n')
    out.write('    u32 sp = reg[13];\n')
    out.write('    u32 lr = reg[14];\n')
    out.write('    u32 cf = reg[REG_C_FLAG], nf = reg[REG_N_FLAG];\n')
    out.write('    u32 zf = reg[REG_Z_FLAG], vf = reg[REG_V_FLAG];\n')
    out.write('    (void)cf; (void)nf; (void)zf; (void)vf;\n')

    # Entry-point dispatch: jump to E_<addr> based on `ep`.
    if ctx['continuations']:
        out.write('    switch (ep) {\n')
        for c in sorted(ctx['continuations']):
            out.write(f'    case 0x{c:08X}u: goto E_{c:08X};\n')
        out.write(f'    default: break;  /* fall through to function head */\n')
        out.write('    }\n')

    # Emit body, inserting E_<addr> labels at continuation points.
    cont_set = ctx['continuations']
    # We need to know each insn's address to emit labels. Walk insns
    # alongside body_lines doesn't directly work — instead, emit labels
    # right before the comment line (which has the address embedded).
    for kind, text in body_lines:
        if kind == 'comment':
            # Extract addr from the comment "/* AAAAAAAA: ... */"
            try:
                addr_str = text.split('/* ', 1)[1].split(':', 1)[0]
                addr_int = int(addr_str, 16)
                if addr_int in cont_set:
                    out.write(f'E_{addr_int:08X}:\n')
            except (ValueError, IndexError):
                pass
            out.write(f'    {text}\n')
        elif kind == 'label':
            out.write(f'{text}\n')
        else:
            out.write(f'    {text}\n')

    out.write('    AOT_RETURN();\n')
    out.write('}\n\n')

    if skipped:
        out.write(f'/* 0x{pc:08X} BAILs ({len(skipped)}): ')
        out.write(', '.join(f'{m}@{a:08X}' for a, m, _ in skipped[:8]))
        if len(skipped) > 8:
            out.write(f', +{len(skipped)-8} more')
        out.write(' */\n\n')

    # Return list of all entry PCs that the dispatch table should
    # register for this function.
    return [pc] + sorted(ctx['continuations'])


if __name__ == '__main__':
    main()
